# Generated by Django 5.2.8 on 2025-11-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_joining',
        ),
    ]
