# Generated by Django 5.2.8 on 2025-11-27 05:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, unique=True)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('instructor', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('credits', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('max_students', models.IntegerField(default=50)),
                ('enrolled_count', models.IntegerField(default=0)),
                ('mode', models.CharField(default='On-campus', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['course_code', 'term'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50, unique=True)),
                ('template', models.TextField()),
                ('variations', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['intent'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('assignment_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('max_marks', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('submission_type', models.CharField(max_length=50)),
                ('allow_late', models.BooleanField(default=False)),
                ('late_penalty', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lms_core.course')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.CharField(max_length=50, unique=True)),
                ('topic', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateField()),
                ('posts_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('status', models.CharField(default='Open', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='lms_core.course')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('quiz_type', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('attempts_allowed', models.CharField(max_length=20)),
                ('time_limit', models.BooleanField(default=True)),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms_core.course')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('program', models.CharField(max_length=100)),
                ('enrollment_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('gpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('address', models.TextField(blank=True)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('international', models.BooleanField(default=False)),
                ('scholarship', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(max_length=20, unique=True)),
                ('query_text', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('response_text', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='lms_core.student')),
            ],
            options={
                'verbose_name_plural': 'Queries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(max_length=20, unique=True)),
                ('assessment_id', models.CharField(max_length=50)),
                ('assessment_type', models.CharField(max_length=20)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_marks', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('submitted_date', models.DateTimeField()),
                ('graded_date', models.DateTimeField()),
                ('feedback', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lms_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lms_core.student')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=20, unique=True)),
                ('enrollment_date', models.DateField()),
                ('role', models.CharField(default='Student', max_length=20)),
                ('status', models.CharField(default='Enrolled', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_core.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_core.student')),
            ],
            options={
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
