# Generated by Django 5.2.8 on 2026-01-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0002_alter_student_enrollment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='query_id',
        ),
    ]
