# Generated by Django 5.2.8 on 2026-01-01 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_core', '0003_remove_query_query_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=50)),
                ('pattern_text', models.TextField()),
                ('examples', models.JSONField(default=list)),
                ('synonyms', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('original_query', models.TextField()),
                ('corrected_query', models.TextField()),
                ('intent', models.CharField(max_length=50)),
                ('entities', models.JSONField(default=dict)),
                ('response_text', models.TextField()),
                ('confidence', models.FloatField()),
                ('processing_time', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('entities', models.JSONField(default=dict)),
                ('last_query', models.TextField(blank=True, null=True)),
                ('last_response', models.TextField(blank=True, null=True)),
                ('context_data', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['session_id', 'is_active'], name='lms_core_co_session_13edae_idx')],
            },
        ),
    ]
